displayName=Nice.
author=peepoBlush
description=Takes a screenshot whenever you deal 69 damage while your character says "Nice."
tags=
version=
plugins=org.nice.Damage69ScreenshotPlugin
build=standard
